# Generated by Django 4.1.7 on 2023-06-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foodie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.TextField()),
                ('items', models.TextField()),
                ('lat_long', models.BigIntegerField()),
                ('full_details', models.TextField()),
            ],
        ),
    ]
