# Generated by Django 4.1.7 on 2023-06-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodie',
            name='lat_long',
            field=models.IntegerField(verbose_name='lat_long'),
        ),
    ]
