# Generated by Django 4.1.7 on 2023-06-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0002_alter_foodie_lat_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodie',
            name='lat_long',
            field=models.TextField(),
        ),
    ]
